apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: load-gen-node-ingress
  namespace: application
  annotations:
    konghq.com/strip-path: "true" # Remove o prefixo /load-gen-node antes de enviar para o app
    konghq.com/protocol: "http"
    konghq.com/service-upstream: "true"
    ingress.kubernetes.io/service-upstream: "true"
    konghq.com/preserve-host: "false" 
spec:
  ingressClassName: kong # Define que o Kong deve gerenciar este Ingress
  rules:
    - http:
        paths:
          - path: /load-gen-node
            pathType: Prefix
            backend:
              service:
                name: load-gen-node-service
                port:
                  number: 80
