apiVersion: v1
kind: Service
metadata:
  name: project-a-service
  namespace: application
spec:
  selector:
    app: project-a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
