# Valores customizados para o Istio
# Geralmente o Istio é instalado via istioctl ou Helm charts específicos (base, discovery)
global:
  proxy:
    resources:
      requests:
        cpu: 10m
        memory: 40Mi

meshConfig:
  extensionProviders:
    - name: "otel-tracing"
      otel:
        service: "signoz-otel-collector.platform.svc.cluster.local"
        port: 4318
  defaultProviders:
    tracing:
      - "otel-tracing"