apiVersion: v1
kind: Service
metadata:
  name: project-b-service
  namespace: application
spec:
  selector:
    app: project-b
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
