apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: load-gen-node-ingress
  namespace: application
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: load-gen.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: load-gen-node-service
                port:
                  number: 80
